services:
  ghi:
    image: node:16.11.1-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./tokyo:/app
    ports:
        - "3000:3000"
    environment:
        NODE_ENV: development
        HOST: "0.0.0.0"
